# working with dates and time

In [155]:
import pandas as pd
import numpy as np

In [156]:
date = pd.read_csv('/content/orders.csv')
time = pd.read_csv('/content/messages.csv')

In [157]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [158]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [159]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

# Working with dates

In [160]:
# converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [161]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [162]:
date.drop(columns=['product_id',	'city_id',	'orders'], inplace = True)
date

          date
0   2019-12-10
1   2018-08-15
2   2018-10-23
3   2019-08-17
4   2019-01-06
..         ...
995 2018-10-08
996 2018-12-06
997 2019-05-07
998 2019-03-03
999 2019-10-15

[1000 rows x 1 columns]

##Extract year

In [163]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  date_year
55  2019-07-26       2019
615 2018-10-19       2018
938 2019-06-21       2019
824 2018-09-24       2018
169 2019-03-25       2019

## Extract Month

In [164]:
date['date_month_no'] = date['date'].dt.month
date.sample(5)

          date  date_year  date_month_no
505 2019-12-12       2019             12
827 2019-07-05       2019              7
691 2019-06-22       2019              6
96  2018-08-23       2018              8
317 2018-08-31       2018              8

In [165]:
date['date_month_name'] = date['date'].dt.month_name()
date.sample(5)

          date  date_year  date_month_no date_month_name
639 2019-11-04       2019             11        November
137 2019-03-14       2019              3           March
282 2019-10-27       2019             10         October
788 2018-11-03       2018             11        November
38  2019-02-15       2019              2        February

## Extract dates

In [166]:
date['date_day'] = date['date'].dt.day
date.sample(5)

          date  date_year  date_month_no date_month_name  date_day
647 2018-09-05       2018              9       September         5
850 2018-12-28       2018             12        December        28
248 2019-01-04       2019              1         January         4
652 2019-10-29       2019             10         October        29
272 2019-10-22       2019             10         October        22

In [167]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek
date.sample(5)

          date  date_year  date_month_no date_month_name  date_day  date_dow
231 2018-08-28       2018              8          August        28         1
839 2018-09-23       2018              9       September        23         6
57  2019-08-04       2019              8          August         4         6
583 2019-05-17       2019              5             May        17         4
897 2018-10-09       2018             10         October         9         1

In [168]:
# day of week name
date['date_dow_name'] = date['date'].dt.day_name()
date.sample(5)

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
237,2019-12-09,2019,12,December,9,0,Monday
640,2018-11-03,2018,11,November,3,5,Saturday
374,2018-12-16,2018,12,December,16,6,Sunday
266,2019-12-11,2019,12,December,11,2,Wednesday
488,2019-10-30,2019,10,October,30,2,Wednesday

## Extract week of the year

In [169]:
date['date_week'] = date['date'].dt.isocalendar().week
date.sample(5)

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_week
832,2019-01-11,2019,1,January,11,4,Friday,2
856,2019-10-18,2019,10,October,18,4,Friday,42
573,2018-12-16,2018,12,December,16,6,Sunday,50
229,2019-11-29,2019,11,November,29,4,Friday,48
844,2019-04-03,2019,4,April,3,2,Wednesday,14

## Extract Quarter

In [170]:
date['quarter'] = date['date'].dt.quarter
date.sample(5)

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_week,quarter
344,2018-12-22,2018,12,December,22,5,Saturday,51,4
249,2018-12-14,2018,12,December,14,4,Friday,50,4
26,2019-01-09,2019,1,January,9,2,Wednesday,2,1
28,2019-04-20,2019,4,April,20,5,Saturday,16,2
93,2019-11-12,2019,11,November,12,1,Tuesday,46,4

## Extract Semester

In [171]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)
date.sample(5)

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_week,quarter,semester
207,2019-04-01,2019,4,April,1,0,Monday,14,2,1
116,2019-04-23,2019,4,April,23,1,Tuesday,17,2,1
829,2019-09-18,2019,9,September,18,2,Wednesday,38,3,2
525,2019-06-13,2019,6,June,13,3,Thursday,24,2,1
625,2018-10-05,2018,10,October,5,4,Friday,40,4,2

## extract time elasped between dates

In [172]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 8, 13, 3, 48, 53, 769778)

In [173]:
today - date['date']

0     2438 days 03:48:53.769778
1     2920 days 03:48:53.769778
2     2851 days 03:48:53.769778
3     2553 days 03:48:53.769778
4     2776 days 03:48:53.769778
                 ...
995   2866 days 03:48:53.769778
996   2807 days 03:48:53.769778
997   2655 days 03:48:53.769778
998   2720 days 03:48:53.769778
999   2494 days 03:48:53.769778
Name: date, Length: 1000, dtype: timedelta64[ns]

In [174]:
(today - date['date']).dt.days

0      2438
1      2920
2      2851
3      2553
4      2776
       ...
995    2866
996    2807
997    2655
998    2720
999    2494
Name: date, Length: 1000, dtype: int64

In [175]:
# month passed
date['months_passed'] = np.round((today - date['date']) / np.timedelta64(1, 'D') / 30.44,0)
date.sample(5)

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_week,quarter,semester,months_passed
347,2019-01-16,2019,1,January,16,2,Wednesday,3,1,1,91.0
653,2019-02-27,2019,2,February,27,2,Wednesday,9,1,1,89.0
396,2019-10-25,2019,10,October,25,4,Friday,43,4,2,82.0
148,2019-12-10,2019,12,December,10,1,Tuesday,50,4,2,80.0
147,2019-12-09,2019,12,December,9,0,Monday,50,4,2,80.0

# Working with time

In [176]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [177]:
time['date'] = pd.to_datetime(time['date'])

In [178]:
time.sample(5)

                   date                                                msg
432 2012-09-16 00:34:00  парень  42 лет ищет пару мущ и жен 0982358952 смс
160 2014-05-20 00:43:00  Симп Мужчина! Желает завтра встр с дев.жен для...
386 2012-09-14 23:58:00  Ж-38 лет.Если вы НЕ озабоченный неудачник звон...
188 2016-04-11 00:36:00        П25 пообщаюсь с симпотичной д\\ж 0957621101
107 2012-09-15 00:34:00  приветос Модер.спасибо с третьего раза песню п...

In [179]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [180]:
time.drop(columns=['msg'], inplace = True)

In [181]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

                 date  hour  min  sec
0 2013-12-15 00:50:00     0   50    0
1 2014-04-29 23:40:00    23   40    0
2 2012-12-30 00:21:00     0   21    0
3 2014-11-28 00:31:00     0   31    0
4 2013-10-26 23:11:00    23   11    0

## Extract Time part

In [182]:
time['time'] = time['date'].dt.time
time.head()

                 date  hour  min  sec      time
0 2013-12-15 00:50:00     0   50    0  00:50:00
1 2014-04-29 23:40:00    23   40    0  23:40:00
2 2012-12-30 00:21:00     0   21    0  00:21:00
3 2014-11-28 00:31:00     0   31    0  00:31:00
4 2013-10-26 23:11:00    23   11    0  23:11:00

## time difference

In [183]:
today - time['date']

0     4624 days 02:58:53.769778
1     4488 days 04:08:53.769778
2     4974 days 03:27:53.769778
3     4276 days 03:17:53.769778
4     4673 days 04:37:53.769778
                 ...
995   5263 days 02:58:53.769778
996   4584 days 04:34:53.769778
997   5049 days 04:11:53.769778
998   5165 days 04:14:53.769778
999   4437 days 04:23:53.769778
Name: date, Length: 1000, dtype: timedelta64[ns]

In [184]:
# in second

(today - time['date']) / np.timedelta64(1, 's')

0      3.995243e+08
1      3.877781e+08
2      4.297661e+08
3      3.694583e+08
4      4.037639e+08
           ...
995    4.547339e+08
996    3.960741e+08
997    4.362487e+08
998    4.462713e+08
999    3.833726e+08
Name: date, Length: 1000, dtype: float64

In [185]:
# in minute

(today - time['date']) / np.timedelta64(1, 'm')

0      6.658739e+06
1      6.462969e+06
2      7.162768e+06
3      6.157638e+06
4      6.729398e+06
           ...
995    7.578899e+06
996    6.601235e+06
997    7.270812e+06
998    7.437855e+06
999    6.389544e+06
Name: date, Length: 1000, dtype: float64

In [186]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      110978.981603
1      107716.148269
2      119379.464936
3      102627.298269
4      112156.631603
           ...
995    126314.981603
996    110020.581603
997    121180.198269
998    123964.248269
999    106492.398269
Name: date, Length: 1000, dtype: float64