In [72]:
import numpy as np
import pandas as pd

In [73]:
df = pd.read_csv('/content/customer.csv')

In [74]:
df.sample(5)

    age  gender review education purchased
43   27    Male   Poor        PG        No
33   89  Female   Good        PG       Yes
18   19    Male   Good    School        No
1    68  Female   Poor        UG        No
25   57  Female   Good    School        No

In [75]:
df = df.iloc[:, 2:]

In [76]:
df.sample(5)

     review education purchased
3      Good        PG        No
49     Good        UG        No
39     Poor        PG        No
30  Average        UG        No
37  Average        PG       Yes

In [77]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:2], df.iloc[:, -1], test_size=0.2)

In [78]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(40, 2)
(10, 2)
(40,)
(10,)

## ordinal encoding

In [79]:
from sklearn.preprocessing import OrdinalEncoder

In [80]:
X_train.sample(5)

     review education
48     Good        UG
44  Average        UG
16     Poor        UG
25     Good    School
1      Poor        UG

In [81]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [82]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [83]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [84]:
X_train

array([[1., 0.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [2., 2.],
       [1., 2.],
       [1., 0.],
       [2., 0.],
       [2., 2.],
       [1., 2.]])

In [85]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [86]:
from sklearn.preprocessing import LabelEncoder

In [87]:
le = LabelEncoder()

In [88]:
le.fit(y_train)

LabelEncoder()

In [89]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [90]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [91]:
y_train

array([0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0])

In [92]:
y_test

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 1])

In [93]:
X_test

array([[1., 1.],
       [0., 1.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.]])

In [94]:
X_train

array([[1., 0.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [2., 2.],
       [1., 2.],
       [1., 0.],
       [2., 0.],
       [2., 2.],
       [1., 2.]])

### covert np.array in data frame

In [95]:
# X_train = pd.DataFrame(
#     X_train,
#     columns=['Gender', 'Education']
# )

# X_test = pd.DataFrame(
#     X_test,
#     columns=['Gender', 'Education']
# )

In [96]:
# y_train = pd.DataFrame(
#     y_train,
#     columns=['purchased']
# )

# y_test = pd.DataFrame(
#     y_test,
#    columns=['purchased']
# )